### ISSUE TITLE
nx8-500s.sinc

### ISSUE THREAD

**Issue by mumbel** [a1k0n/ghidra-msm66q59x#1]
Looks like you missed a git add

**Comment by a1k0n** [comment]
oh, oops, you're right. it's autogenerated so I was intentionally not committing it, but the source data is in another repo anyway. Added.

**Comment by a1k0n** [comment]
that's what the README meant, BTW.

> work in progress right now; you need to run the sleigh.py script from my asm66q59x repo to generate the .sinc file in data/languages/

**Comment by mumbel** [comment]
oops skipped README and just went to data/languages, thanks for adding it.
